version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - TZ=Asia/Vladivostok
    container_name: sk_prod_backend
    restart: always
    env_file: .env
    # В проде убираем --reload для производительности
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      # Важно: прокидываем файл базы данных, чтобы он сохранялся на сервере
      # Файл history.db будет лежать в папке sk_data на сервере
      - ./sk_data/history.db:/app/history.db
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod # Указываем использовать именно PROD файл
    container_name: sk_prod_frontend
    restart: always
    depends_on:
      - backend
    ports:
      # Внутренний 80 порт фронта выставляем на 8080 порта сервера
      - "127.0.0.1:8080:80"